Checking identifier value

diff --git a/.github/workflows/promote_package.yml b/.github/workflows/promote_package.yml
--- a/.github/workflows/promote_package.yml
+++ b/.github/workflows/promote_package.yml
@@ -46,15 +46,13 @@ jobs:
           
           # Extract the identifier_perm using jq
           IDENTIFIER=$(echo "$PACKAGE_DATA" | jq -r '.data[0].identifier_perm')
-
+          
+          # if [ -z "$IDENTIFIER" ] || [ "$IDENTIFIER" = "null" ]; then
+          #   echo "Failed to find package identifier"
+          #   exit 1
+          # fi
+          
           cloudsmith tags add ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER ready-for-production
-
-          
-          if [ -z "$IDENTIFIER" ] || [ "$IDENTIFIER" = "null" ]; then
-            echo "Failed to find package identifier"
-            exit 1
-          fi
-          
           echo "Found package identifier: $IDENTIFIER"
           
           # Promote package using the identifier
